### ISSUE TITLE
Installation problem : pserve Exception: Missing global configuration file 

### ISSUE THREAD

**Issue by vloux** [genouest/biomaj-watcher#21]
Dear biomaj developers,
we try to install biomaj-watcher by following the instructions in README.md

We finally got to the point where we try to start the server. We have edited the development.ini file to point it to our biomaj3 global.properties . At startup pserve raise the following error :
```
(biomaj-watcher-042017) [banko@banko3 biomaj-watcher]$ pserve - development.ini
Traceback (most recent call last):
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/bin/pserve", line 11, in <module>
    load_entry_point('pyramid', 'console_scripts', 'pserve')()
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/scripts/pserve.py", line 51, in main
    return command.run()
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/scripts/pserve.py", line 316, in run
    global_conf=vars)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/scripts/pserve.py", line 340, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/biomaj-watcher/biomajwatcher/__init__.py", line 34, in main
    BiomajConfig.load_config(config['biomaj']['config'])
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/biomaj_core-3.0.7-py2.7.egg/biomaj_core/config.py", line 89, in load_config
    raise Exception('Missing global configuration file')
Exception: Missing global configuration file 
```

Have we missed a specific configuration step ?  
Best regards

**Comment by horkko** [comment]
Hi,

I think you've got an unexpected hyphen '-' argument on your command line `pserve - development.ini`
Maybe this is the problem?

**Comment by vloux** [comment]
Hi,
thanks for your answer. Sorry , it was a copy-paste mistake. There is no hyphen in the command-line.
 Here is the right output for the command 

```
(biomaj-watcher-042017) [banko@banko3 biomaj-watcher]$ pserve  development.ini
Traceback (most recent call last):
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/bin/pserve", line 11, in <module>
    load_entry_point('pyramid', 'console_scripts', 'pserve')()
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/scripts/pserve.py", line 51, in main
    return command.run()
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/scripts/pserve.py", line 316, in run
    global_conf=vars)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/scripts/pserve.py", line 340, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/biomaj-watcher/biomajwatcher/__init__.py", line 34, in main
    BiomajConfig.load_config(config['biomaj']['config'])
  File "/usr/local/banko/VirtualEnv/biomaj-watcher-042017/lib/python2.7/site-packages/biomaj_core-3.0.7-py2.7.egg/biomaj_core/config.py", line 89, in load_config
    raise Exception('Missing global configuration file')
Exception: Missing global configuration file 
```

**Comment by osallou** [comment]
biomaj-watcher reads some config from file config.yml, located in current directory or specified via BIOMAJ_CONFIG env variable.


path to global .properties must be specified both in config.yml and development/production.ini

**Comment by vloux** [comment]
> path to global .properties must be specified both in config.yml and development/production.ini

That was it ! Thanks
